---
- name: Installation des services Apache
  hosts: apache
  become: true
  vars:
    ansible_become_pass: "root"

  tasks:
    # -------------- Installe Apache et les dépendances --------------
    - name: Installe Apache et dépendances
      apt:
        name:
          - apache2
          - php
          - unzip
          - curl
          - git
        state: present

    - name: Active les modules Apache nécessaires
      apache2_module:
        state: present
        name: rewrite

    # -------------- Crée les dossiers pour les services --------------
    - name: Crée les dossiers pour les services web
      file:
        path: "/var/www/html/{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      with_items:
        - filegator
        - freshrss
        - glpi
        - nextcloud

    # -------------- Télécharge et Installe FileGator (ZIP) --------------
    - name: Télécharge FileGator
      get_url:
        url: "https://github.com/filegator/filegator/archive/refs/tags/v7.12.0.zip"
        dest: "/tmp/filegator.zip"

    - name: Décompresse FileGator avec unzip
      shell:
        cmd: "unzip -o /tmp/filegator.zip -d /var/www/html/filegator && mv /var/www/html/filegator/filegator-*/* /var/www/html/filegator/"
        creates: "/var/www/html/filegator/index.php"

    - name: Ajuste les permissions de FileGator
      file:
        path: "/var/www/html/filegator"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    # -------------- Télécharge et Installe FreshRSS --------------
    - name: Télécharge FreshRSS via Git
      git:
        repo: "https://github.com/FreshRSS/FreshRSS.git"
        dest: "/var/www/html/freshrss"
        version: main
        depth: 1
        force: yes
      environment:
        GIT_SSL_NO_VERIFY: "true"

    - name: Ajuste les permissions de FreshRSS
      file:
        path: "/var/www/html/freshrss"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data


    # -------------- Télécharge et Installe GLPI (TAR) --------------
    - name: Télécharge GLPI
      get_url:
        url: "https://github.com/glpi-project/glpi/releases/download/10.0.13/glpi-10.0.13.tgz"
        dest: "/tmp/glpi.tgz"

    - name: Décompresser GLPI
      unarchive:
        src: "/tmp/glpi.tgz"
        dest: "/var/www/html/glpi"
        remote_src: yes
        owner: www-data
        group: www-data

    # -------------- Télécharge et Installe Nextcloud (ZIP) --------------
    - name: Télécharge Nextcloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/latest.zip"
        dest: "/tmp/nextcloud.zip"

    - name: Décompresser Nextcloud avec unzip
      shell:
        cmd: "unzip -o /tmp/nextcloud.zip -d /var/www/html/nextcloud"
        creates: "/var/www/html/nextcloud/index.php"

    - name: Ajuste les permissions de Nextcloud
      file:
        path: "/var/www/html/nextcloud"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    # -------------- Crée et Active les VHosts --------------
    - name: Crée les Vhosts
      copy:
        dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
        content: |
          <VirtualHost *:80>
              ServerName {{ item.domain }}
              DocumentRoot /var/www/html/{{ item.name }}
              <Directory /var/www/html/{{ item.name }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/{{ item.name }}_error.log
              CustomLog ${APACHE_LOG_DIR}/{{ item.name }}_access.log combined
          </VirtualHost>
      with_items:
        - { name: 'filegator', domain: 'files.domaine.local' }
        - { name: 'freshrss', domain: 'news.domaine.local' }
        - { name: 'glpi', domain: 'support.domaine.local' }
        - { name: 'nextcloud', domain: 'cloud.domaine.local' }

    - name: Activer les Vhosts
      command: a2ensite {{ item.name }}
      with_items:
        - { name: 'filegator' }
        - { name: 'freshrss' }
        - { name: 'glpi' }
        - { name: 'nextcloud' }

    # -------------- Redémarre Apache --------------
    - name: Redémarrer Apache
      systemd:
        name: apache2
        state: restarted
