---
- name: Installation des services Apache
  hosts: apache
  become: true
  vars:
    ansible_become_pass: "root"  # Mot de passe root pour la VM en distance

  tasks:
    # -------------- Installe Apache et les dépendances --------------
    - name: Installer Apache et dépendances
      apt:
        name:
          - apache2
          - php
          - unzip
          - curl
          - git
        state: present

    - name: Activer les modules Apache nécessaires
      apache2_module:
        state: present
        name: rewrite

    # -------------- Crée les dossiers pour les services --------------
    - name: Créer les dossiers pour les services web
      file:
        path: "/var/www/html/{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      with_items:
        - filegator
        - freshrss
        - glpi
        - nextcloud

    # -------------- Télécharge et Installe FileGator --------------
    - name: Télécharger FileGator
      get_url:
        url: "https://github.com/filegator/filegator/archive/refs/tags/v7.12.0.zip"
        dest: "/tmp/filegator.zip"

    - name: Décompresser FileGator
      unarchive:
        src: "/tmp/filegator.zip"
        dest: "/var/www/html/filegator"
        remote_src: yes
        owner: www-data
        group: www-data
        extra_opts: [--strip-components=1]

    # -------------- Télécharge et Installe FreshRSS --------------
    - name: Télécharger FreshRSS
      git:
        repo: "https://github.com/FreshRSS/FreshRSS.git"
        dest: "/var/www/html/freshrss"
        version: master

    # -------------- Télécharge et Installe GLPI --------------
    - name: Télécharger GLPI
      get_url:
        url: "https://github.com/glpi-project/glpi/releases/download/10.0.13/glpi-10.0.13.tgz"
        dest: "/tmp/glpi.tgz"

    - name: Décompresser GLPI
      unarchive:
        src: "/tmp/glpi.tgz"
        dest: "/var/www/html/glpi"
        remote_src: yes
        owner: www-data
        group: www-data
        extra_opts: [--strip-components=1]

    # -------------- Télécharge et Installe Nextcloud --------------
    - name: Télécharger Nextcloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/latest.zip"
        dest: "/tmp/nextcloud.zip"

    - name: Décompresser Nextcloud
      unarchive:
        src: "/tmp/nextcloud.zip"
        dest: "/var/www/html/nextcloud"
        remote_src: yes
        owner: www-data
        group: www-data
        extra_opts: [--strip-components=1]

    # -------------- Crée et Active les VHosts --------------
    - name: Créer les Vhosts
      copy:
        dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
        content: |
          <VirtualHost *:80>
              ServerName {{ item.domain }}
              DocumentRoot /var/www/html/{{ item.name }}
              <Directory /var/www/html/{{ item.name }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/{{ item.name }}_error.log
              CustomLog ${APACHE_LOG_DIR}/{{ item.name }}_access.log combined
          </VirtualHost>
      with_items:
        - { name: 'filegator', domain: 'files.domaine.local' }
        - { name: 'freshrss', domain: 'news.domaine.local' }
        - { name: 'glpi', domain: 'support.domaine.local' }
        - { name: 'nextcloud', domain: 'cloud.domaine.local' }

    - name: Activer les Vhosts
      command: a2ensite {{ item.name }}
      with_items:
        - { name: 'filegator' }
        - { name: 'freshrss' }
        - { name: 'glpi' }
        - { name: 'nextcloud' }

    # -------------- Redémarre Apache --------------
    - name: Redémarrer Apache
      systemd:
        name: apache2
        state: restarted
